export interface IDiscordGuildData {
	"id" : string,
	"name" : string,
	"icon" : null | string,
	"features" : string[],
	"commands" : string[],
	"members" : string[],
	"channels" : string[],
	"bans" : string[],
	"roles" : string[],
	"stageInstances" : [],
	"invites" : [],
	"scheduledEvents" : [],
	"autoModerationRules" : [],
	"shardId" : number,
	"splash" : null | string,
	"banner" : null | string,
	"description" : null | string,
	"verificationLevel" : 1,
	"vanityURLCode" : null | string,
	"nsfwLevel" : number,
	"premiumSubscriptionCount" : number,
	"discoverySplash" : null | string,
	"memberCount" : number,
	"large" : boolean,
	"premiumProgressBarEnabled" : boolean,
	"applicationId" : null | string,
	"afkTimeout" : number,
	"afkChannelId" : null | string,
	"systemChannelId" : string,
	"premiumTier" : number,
	"widgetEnabled" : null | string,
	"widgetChannelId" : null | string,
	"explicitContentFilter" : number,
	"mfaLevel" : number,
	"joinedTimestamp" : string,
	"defaultMessageNotifications" : number,
	"systemChannelFlags" : number,
	"maximumMembers" : number,
	"maximumPresences" : null | string,
	"maxVideoChannelUsers" : number,
	"maxStageVideoChannelUsers" : number,
	"approximateMemberCount" : null | string,
	"approximatePresenceCount" : null | string,
	"vanityURLUses" : null | string,
	"rulesChannelId" : null | string,
	"publicUpdatesChannelId" : null | string,
	"preferredLocale" : string,
	"ownerId" : string,
	"emojis" : string[],
	"stickers" : string[],
	"createdTimestamp" : number,
	"nameAcronym" : string,
	"iconURL" : null | string,
	"splashURL" : null | string,
	"discoverySplashURL" : null | string,
	"bannerURL" : null | string
}