name: Build, Push and Deploy

on:
    push:
        branches:
            - 'main'
            - 'dev'
            - 'next'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    DOCKERNAME: ${{ github.ref == 'refs/heads/main' && 'kbot2' || 'dev-kbot2' }}

jobs:
    prepare-and-build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: lint and type check
              env:
                  NEXTAUTH_SECRET: "will pass in as env var in production"
                  DISCORD_CLIENT_SECRET: "will pass in as env var in production"
                  DISCORD_BOT_TOKEN: "will pass in as env var in production"
                  NEXTAUTH_URL: "will pass in as env var in production"
                  REDIS_PASSWORD: "will pass in as env var in production"
                  REDIS_HOST: "will pass in as env var in production"
                  REDIS_PORT: "1000"
                  POSTGRES_PASSWORD: "will pass in as env var in production"
                  POSTGRES_USER: "will pass in as env var in production"
                  POSTGRES_DB: "will pass in as env var in production"
                  POSTGRES_HOST: "will pass in as env var in production"
                  POSTGRES_PORT: "1000"
                  FICSIT_APP_API_URL: "will pass in as env var in production"
                  FICSIT_APP_API_TOKEN: "will pass in as env var in production"
                  DISCORD_CLIENT_ID: ${{ github.ref == 'refs/heads/main' && '944331343700054056' || '1235530228701597778' }}
              run: |
                  pnpm add -g bun
                  pnpm i
                  bun run build

            - name: Log into registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@1294d94f8ee362ab42b6da04c35f4cd03a0e6af7
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      cd /home/apps/ 
                      docker compose up -d --no-deps --pull always --build ${{ env.DOCKERNAME }}
                      docker image prune --force
                      sleep 60
                      docker compose logs ${{ env.DOCKERNAME }}

            - name: 'Create Release'
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              env:
                  GH_TOKEN: ${{ secrets.RELEASE }}
                  GITHUB_TOKEN: ${{ secrets.RELEASE }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  HUSKY: 0
              run: |
                  pnpm semantic-release